### ISSUE TITLE
session에서 dept를 참조하는 문제 - LazyInitializationException

### ISSUE THREAD

**Issue by subin9804** [subin9804/starducks#73]
org.hibernate.LazyInitializationException: could not initialize proxy [org.kosta.starducks.hr.entity.Department#2] - no Session
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:164) ~[hibernate-core-6.3.1.Final.jar:6.3.1.Final]
	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:310) ~[hibernate-core-6.3.1.Final.jar:6.3.1.Final]
	at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:44) ~[hibernate-core-6.3.1.Final.jar:6.3.1.Final]
	at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:102) ~[hibernate-core-6.3.1.Final.jar:6.3.1.Final]

@AuthenticationPrincipal 으로 세션에서 employee 전체의 정보를 받아올 수 있으나 LAZY Loading으로 인해 참조된 department의 정보는 가져오지 못하는 것 같습니다.
그래서 저는 Session에서는 단순히 empId만 받아와서 직접 DB에서 empId로 사원 정보를 찾아내는 방법을 사용했습니다. 다른 방법이 있다면 공유해주세요!

1. empId만 받아오려면 @AuthenticationPrincipal 을 사용해도 좋지만, 단순히 Principal객체를 통해 getName()메서드를 이용하면 Id만 간단하게 받아올 수 있습니다 (편한 방법을 사용해주세용)

<<기존 코드>>
```
    @GetMapping
    public String index(Model model, @AuthenticationPrincipal CustomUserDetails details) {

        Employee emp = empService.getEmp(1L);
        // 유저 정보 받아오기
        if(details != null) {
            emp = details.getEmployee();

        }
        // 화면에 전달
        model.addAttribute("emp", emp);

        model.addAttribute("rooms", ConfRoomEN.values());
        return "mypage/confRoom/confList";
    }
```

<< 수정한 코드>>
```
    @GetMapping
    public String index(Model model, Principal principal) {

        Long empId = 1L;     // 로그인이 안되어 있을 경우 임의의 아이디

        // 유저 정보 받아오기
        if(principal != null) {
            empId = Long.valueOf(principal.getName()); // 로그인이 되어 있을 경우 해당 사원의 아이디를 가져옴
        }

        Employee employee = empService.getEmp(empId);

        model.addAttribute("employee", employee);

        // 화면에 전달
        model.addAttribute("emp", emp);

        model.addAttribute("rooms", ConfRoomEN.values());
        return "mypage/confRoom/confList";
    }

```

**Comment by lhg0529** [comment]
채팅창에서 사원 목록 불러올 때 잘 써먹었습니다

**Comment by jiyoung0307** [comment]
마이페이지에서 잘 써먹을게여
